/**
 * Skill-Based Workflow - Novel creation workflow using SkillOrchestrator
 *
 * Refactored from auto-create-workflow.ts to use the skill infrastructure:
 * - SkillOrchestrator for skill chain execution
 * - Skill loop controller for iteration decisions
 * - Reference library integration
 *
 * Pipeline: bootstrap → outline → scene-plan → write → evaluate → (revision loop)
 */

import type { Project, TargetLength } from '@packages/shared-types';
import {
  SkillOrchestrator,
  type OrchestrationState,
  type OrchestrationHistoryEntry,
} from '@/lib/skills/skill-orchestrator';
import { getSkill } from '@/lib/skills/skill-registry';
import {
  handleBootstrapSkill,
  handleOutlineSkill,
  handleScenePlanSkill,
  handleWriteSkill,
  handleEvaluateSkill,
  handleRevisionSkill,
  configureSkills,
  type SkillConfiguration,
  type ReferenceExample,
  type TechniqueDirective,
} from '@/lib/skills';
import type {
  BootstrapSkillInput,
  OutlineSkillInput,
  ScenePlanSkillInput,
  WriteSkillInput,
  EvaluateSkillInput,
  RevisionSkillInput,
  SkillOutputSchema,
  EvaluateSkillOutput,
} from '@/lib/skills/skill-interface';
import { computeLoopDecision, type LoopDecision } from '@/lib/skills/skill-loop-controller';
import { projectStore, chapterStore, draftSegmentStore } from '@/lib/db/projects-store';
import { loadCollection, saveCollection } from '@/lib/db/file-storage';
import type { BookOutline, Chapter } from '@packages/shared-types';

export type SkillWorkflowStepName =
  | 'charter'
  | 'outline'
  | 'import_chapters'
  | 'chapters'
  | 'evaluation'
  | 'revision';

interface SkillWorkflowChapterReport {
  chapterId: string;
  chapterTitle: string;
  sceneCount: number;
  draftSegments: number;
  draftWordCount: number;
  finalWordCount: number;
  targetWordCount: number;
  minWordCount: number;
  expansionPasses: number;
  wordTargetStatus: 'met' | 'missed' | 'blocked';
  wordTargetWarning?: string;
  snapshotLabel?: string;
  evaluationScore?: number;
  issueCount: number;
  revisedIssues: string[];
  failedIssues: Array<{ issueId: string; reason: string }>;
}

interface SkillWorkflowOptions {
  project: Project;
  targetChapters: number;
  runEvaluation: boolean;
  runRevisions: boolean;
  onStepStart?: (step: SkillWorkflowStepName, message?: string) => void;
  onStepProgress?: (step: SkillWorkflowStepName, progress: number, message?: string) => void;
  onStepComplete?: (step: SkillWorkflowStepName, message?: string) => void;
  onChapterProgress?: (message: string | null) => void;
}

export interface SkillWorkflowResult {
  success: boolean;
  results: {
    importedChapterTitles: string[];
    chapterReports: SkillWorkflowChapterReport[];
    totalScenes: number;
    totalDraftSegments: number;
    totalWords: number;
    totalIssues: number;
    totalRevisedIssues: number;
    targetTotalWords: number;
    minTotalWords: number;
    targetWordsPerChapter: number;
    minWordsPerChapter: number;
    chaptersBelowMinimum: number;
    targetAchieved: boolean;
  };
  orchestrationHistory?: OrchestrationHistoryEntry[];
}

export async function runSkillBasedWorkflow(
  options: SkillWorkflowOptions
): Promise<SkillWorkflowResult> {
  const {
    project,
    targetChapters,
    runEvaluation,
    runRevisions,
    onStepStart,
    onStepProgress,
    onStepComplete,
    onChapterProgress,
  } = options;

  const wordTargetPlan = getWordTargetPlan(project.targetLength, targetChapters);
  const orchestrator = new SkillOrchestrator();

  // Step 0: Configure skills with intelligent technique recommendations
  const skillConfig: SkillConfiguration = configureSkills({
    projectId: project.id,
    title: project.name || project.title || '未命名小说',
    description: project.description,
    bookType: project.bookType,
    targetLength: project.targetLength,
    tags: project.tags,
    charter: undefined, // Will be generated by bootstrap
  });

  const result: SkillWorkflowResult = {
    success: true,
    results: {
      importedChapterTitles: [],
      chapterReports: [],
      totalScenes: 0,
      totalDraftSegments: 0,
      totalWords: 0,
      totalIssues: 0,
      totalRevisedIssues: 0,
      targetTotalWords: wordTargetPlan.targetTotalWords,
      minTotalWords: wordTargetPlan.minTotalWords,
      targetWordsPerChapter: wordTargetPlan.targetWordsPerChapter,
      minWordsPerChapter: wordTargetPlan.minWordsPerChapter,
      chaptersBelowMinimum: 0,
      targetAchieved: false,
    },
  };

  try {
    // Step 1: Bootstrap - generate charter and memories
    onStepStart?.('charter', '正在生成 Charter');
    await handleBootstrapSkill({
      projectId: project.id,
      title: project.name || project.title || '未命名小说',
      bookType: project.bookType || 'novel',
      targetLength: project.targetLength || 'mid',
      language: project.language || '中文',
      tags: project.tags || [],
      description: project.description,
    } as BootstrapSkillInput);
    onStepComplete?.('charter', 'Charter 已生成');

    // Step 2: Outline - generate book outline
    onStepStart?.('outline', '正在生成大纲');
    const outlineSkillConfig = skillConfig.skillConfigs['outline-skill'];
    const outlineResult = await handleOutlineSkill({
      projectId: project.id,
      targetLength: project.targetLength === 'short' ? 'short' : project.targetLength === 'long' ? 'long' : 'mid',
      volumeCount: Math.ceil(targetChapters / 3),
      reference_examples: outlineSkillConfig.referenceExamples,
      technique_directives: outlineSkillConfig.techniqueDirectives,
    } as OutlineSkillInput);

    const outline = outlineResult.deliverable as BookOutline | null;
    if (!outline || !outline.volumes) {
      throw new Error('Failed to generate outline');
    }

    const selectedVolumes = selectOutlineVolumes(outline, targetChapters);
    result.results.importedChapterTitles = selectedVolumes.flatMap((volume) =>
      volume.chapters.map((chapter) => chapter.title)
    );
    onStepComplete?.('outline', `已生成 ${result.results.importedChapterTitles.length} 章大纲`);

    // Step 3: Import chapters from outline
    onStepStart?.('import_chapters', '正在导入章节');
    const existingChapters = await chapterStore.getByProject(project.id);
    for (const chapter of existingChapters) {
      await chapterStore.delete(chapter.id);
    }

    // Create chapters from outline
    const importedChapters: Array<{ id: string; title: string; sortOrder: number }> = [];
    let sortOrder = 0;
    for (const volume of selectedVolumes) {
      for (const chapter of volume.chapters) {
        const created = await chapterStore.create({
          projectId: project.id,
          title: chapter.title,
          sortOrder: sortOrder++,
          status: 'planned',
          parentVolumeId: volume.id,
        });
        if (created) {
          importedChapters.push({ id: created.id, title: created.title, sortOrder: created.sortOrder });
        }
      }
    }

    if (importedChapters.length === 0) {
      throw new Error('Skill-based workflow imported 0 chapters.');
    }
    onStepComplete?.('import_chapters', `已导入 ${importedChapters.length} 个章节`);

    // Step 4: Generate chapters (scene plan → write → evaluate loop)
    onStepStart?.(
      'chapters',
      `目标总字数 ${wordTargetPlan.targetTotalWords}，每章至少 ${wordTargetPlan.minWordsPerChapter} 字`
    );

    for (let chapterIndex = 0; chapterIndex < importedChapters.length; chapterIndex++) {
      const chapter = importedChapters[chapterIndex];
      const chapterReport: SkillWorkflowChapterReport = {
        chapterId: chapter.id,
        chapterTitle: chapter.title,
        sceneCount: 0,
        draftSegments: 0,
        draftWordCount: 0,
        finalWordCount: 0,
        targetWordCount: wordTargetPlan.targetWordsPerChapter,
        minWordCount: wordTargetPlan.minWordsPerChapter,
        expansionPasses: 0,
        wordTargetStatus: 'missed',
        wordTargetWarning: undefined,
        snapshotLabel: undefined,
        evaluationScore: undefined,
        issueCount: 0,
        revisedIssues: [],
        failedIssues: [],
      };
      result.results.chapterReports.push(chapterReport);

      onChapterProgress?.(`正在处理第 ${chapterIndex + 1}/${importedChapters.length} 章：${chapter.title}`);
      onStepProgress?.(
        'chapters',
        Math.floor((chapterIndex / importedChapters.length) * 100),
        `开始生成《${chapter.title}》的场景与正文`
      );

      // Scene Plan Skill
      const scenePlanSkillConfig = skillConfig.skillConfigs['scene-plan-skill'];
      const scenePlanResult = await handleScenePlanSkill({
        projectId: project.id,
        chapterId: chapter.id,
        chapterTitle: chapter.title,
        chapterGoal: '',
        reference_examples: scenePlanSkillConfig.referenceExamples,
        technique_directives: scenePlanSkillConfig.techniqueDirectives,
      } as ScenePlanSkillInput);

      const scenes = (scenePlanResult.deliverable as { scenes: Array<{ id: string; title: string }> })?.scenes || [];
      if (scenes.length === 0) {
        console.warn(`Chapter "${chapter.title}" generated 0 scenes, creating default scene`);
        scenes.push({ id: crypto.randomUUID(), title: '默认场景' });
      }

      chapterReport.sceneCount = scenes.length;
      result.results.totalScenes += scenes.length;

      // Write Skill for each scene
      const writeSkillConfig = skillConfig.skillConfigs['write-skill'];
      for (let sceneIndex = 0; sceneIndex < scenes.length; sceneIndex++) {
        const scene = scenes[sceneIndex];

        onStepProgress?.(
          'chapters',
          Math.min(
            Math.floor(((chapterIndex * scenes.length + sceneIndex + 1) / (importedChapters.length * scenes.length)) * 100),
            99
          ),
          `《${chapter.title}》正文生成 ${sceneIndex + 1}/${scenes.length}`
        );

        await handleWriteSkill({
          projectId: project.id,
          chapterId: chapter.id,
          sceneId: scene.id,
          scene: {
            id: scene.id,
            title: scene.title,
            summary: '',
          },
          reference_examples: writeSkillConfig.referenceExamples,
          technique_directives: writeSkillConfig.techniqueDirectives,
        } as WriteSkillInput);

        chapterReport.draftSegments += 1;
        result.results.totalDraftSegments += 1;
      }

      // Expand chapter to target word count
      const expansionResult = await expandChapterToTargetSkill({
        project,
        chapter,
        chapterReport,
        wordTargetPlan,
        onChapterProgress,
        skillConfig,
      });

      chapterReport.finalWordCount = expansionResult.draftPayload.totalWordCount;
      chapterReport.wordTargetWarning = expansionResult.warning;
      chapterReport.wordTargetStatus =
        chapterReport.finalWordCount >= wordTargetPlan.minWordsPerChapter
          ? 'met'
          : expansionResult.warning
            ? 'blocked'
            : 'missed';

      // Create snapshot version
      const snapshotLabel = `自动初始版本-${chapter.title}`;
      chapterReport.snapshotLabel = snapshotLabel;
    }
    onStepComplete?.('chapters', '章节正文与初始版本已完成');

    // Step 5: Evaluation
    if (runEvaluation) {
      onStepStart?.('evaluation', '正在进行章节评估');
      for (let chapterIndex = 0; chapterIndex < importedChapters.length; chapterIndex++) {
        const chapter = importedChapters[chapterIndex];
        onChapterProgress?.(`正在评估第 ${chapterIndex + 1}/${importedChapters.length} 章：${chapter.title}`);

        // Get chapter content
        const segments = await draftSegmentStore.getByChapter(chapter.id);
        const sortedSegments = [...segments].sort((a, b) => a.segmentIndex - b.segmentIndex);
        const content = sortedSegments.map((s) => s.content).join('\n\n');

        // Evaluate
        const evalSkillConfig = skillConfig.skillConfigs['evaluate-skill'];
        const evalResult = await handleEvaluateSkill({
          projectId: project.id,
          chapterId: chapter.id,
          content,
          chapterGoal: '',
          reference_examples: evalSkillConfig.referenceExamples,
          technique_directives: evalSkillConfig.techniqueDirectives,
        } as EvaluateSkillInput);

        const report = result.results.chapterReports[chapterIndex];
        if (report && evalResult.deliverable) {
          const evalOutput = evalResult.deliverable as EvaluateSkillOutput['deliverable'];
          report.evaluationScore = typeof evalOutput.scores.total === 'number' ? evalOutput.scores.total : 0;
          report.issueCount = (evalOutput.revision?.must_fix?.length || 0) + (evalOutput.revision?.should_improve?.length || 0);
        }

        onStepProgress?.(
          'evaluation',
          Math.round(((chapterIndex + 1) / importedChapters.length) * 100),
          `已完成《${chapter.title}》评估`
        );
      }
      onStepComplete?.('evaluation', '章节评估已完成');
    }

    // Step 6: Revision
    if (runRevisions) {
      onStepStart?.('revision', '正在处理评估问题单');
      for (let chapterIndex = 0; chapterIndex < importedChapters.length; chapterIndex++) {
        const chapter = importedChapters[chapterIndex];
        onChapterProgress?.(`正在修订第 ${chapterIndex + 1}/${importedChapters.length} 章：${chapter.title}`);

        const report = result.results.chapterReports[chapterIndex];
        if (report) {
          await processIssuesForChapterSkill(project.id, chapter, report, result, skillConfig);
          const finalDraft = await getDraftWordCount(project.id, chapter.id);
          report.finalWordCount = finalDraft.totalWordCount;
        }

        onStepProgress?.(
          'revision',
          Math.round(((chapterIndex + 1) / importedChapters.length) * 100),
          `已完成《${chapter.title}》问题修订`
        );
      }
      onStepComplete?.('revision', '问题修订与应用已完成');
    }

    // Compute totals
    result.results.totalWords = result.results.chapterReports.reduce(
      (sum, report) => sum + report.finalWordCount,
      0
    );
    result.results.chaptersBelowMinimum = result.results.chapterReports.filter(
      (report) => report.finalWordCount < report.minWordCount
    ).length;
    result.results.targetAchieved =
      result.results.totalWords >= result.results.minTotalWords &&
      result.results.chaptersBelowMinimum === 0;

    result.orchestrationHistory = orchestrator.getHistory();
    onChapterProgress?.(null);

    return result;
  } catch (error) {
    console.error('[SkillBasedWorkflow] Error:', error);
    return {
      success: false,
      results: {
        importedChapterTitles: result.results.importedChapterTitles,
        chapterReports: result.results.chapterReports,
        totalScenes: result.results.totalScenes,
        totalDraftSegments: result.results.totalDraftSegments,
        totalWords: result.results.totalWords,
        totalIssues: result.results.totalIssues,
        totalRevisedIssues: result.results.totalRevisedIssues,
        targetTotalWords: wordTargetPlan.targetTotalWords,
        minTotalWords: wordTargetPlan.minTotalWords,
        targetWordsPerChapter: wordTargetPlan.targetWordsPerChapter,
        minWordsPerChapter: wordTargetPlan.minWordsPerChapter,
        chaptersBelowMinimum: result.results.chaptersBelowMinimum,
        targetAchieved: false,
      },
      orchestrationHistory: orchestrator.getHistory(),
    };
  }
}

// ============================================================
// Helper Functions
// ============================================================

async function expandChapterToTargetSkill({
  project,
  chapter,
  chapterReport,
  wordTargetPlan,
  onChapterProgress,
  skillConfig,
}: {
  project: Project;
  chapter: { id: string; title: string };
  chapterReport: SkillWorkflowChapterReport;
  wordTargetPlan: { targetWordsPerChapter: number; minWordsPerChapter: number };
  onChapterProgress?: (message: string | null) => void;
  skillConfig: SkillConfiguration;
}): Promise<{ draftPayload: { totalWordCount: number }; warning?: string }> {
  let draftPayload = await getDraftWordCount(project.id, chapter.id);
  let attempt = 0;
  let warning: string | undefined;

  while (
    draftPayload.totalWordCount < wordTargetPlan.minWordsPerChapter &&
    attempt < 3
  ) {
    attempt += 1;
    const desiredIncrease = Math.max(
      wordTargetPlan.targetWordsPerChapter - draftPayload.totalWordCount,
      300
    );

    onChapterProgress?.(
      `《${chapter.title}》第 ${attempt} 次扩写，当前 ${draftPayload.totalWordCount}/${wordTargetPlan.minWordsPerChapter} 字`
    );

    try {
      // Use revision skill for expansion
      const segments = await draftSegmentStore.getByChapter(chapter.id);
      const sortedSegments = [...segments].sort((a, b) => a.segmentIndex - b.segmentIndex);
      const lastSegment = sortedSegments[sortedSegments.length - 1];
      const expansionContext = sortedSegments.map((s) => s.content).join('\n\n').slice(-1200);
      const revisionSkillConfig = skillConfig.skillConfigs['revision-skill'];

      await handleRevisionSkill({
        projectId: project.id,
        chapterId: chapter.id,
        segmentId: lastSegment?.id,
        originalText: expansionContext,
        suggestion: `在不改变当前剧情走向的前提下，为本章末段补写约 ${desiredIncrease} 字，增强动作、环境、心理与冲突推进，使章节更接近目标篇幅。`,
        goals: ['扩写章节篇幅', '增强场景真实感', '补足人物动作与心理'],
        constraints: [
          `保留本章既有剧情事实与人物关系`,
          `不要重复前文已经出现的段落`,
          `新增内容应自然衔接在当前末段之后`,
        ],
        applyMode: 'append',
        reference_examples: revisionSkillConfig.referenceExamples,
        technique_directives: revisionSkillConfig.techniqueDirectives,
      } as RevisionSkillInput);

      chapterReport.expansionPasses += 1;
      draftPayload = await getDraftWordCount(project.id, chapter.id);
    } catch (error) {
      warning = error instanceof Error ? error.message : String(error);
      onChapterProgress?.(`《${chapter.title}》扩写被门禁拦截：${warning}`);
      break;
    }
  }

  return { draftPayload, warning };
}

async function processIssuesForChapterSkill(
  projectId: string,
  chapter: { id: string; title: string },
  chapterReport: SkillWorkflowChapterReport,
  workflowResult: SkillWorkflowResult,
  skillConfig: SkillConfiguration
): Promise<void> {
  const issues = await getChapterIssues(projectId, chapter.id);
  chapterReport.issueCount = issues.length;
  workflowResult.results.totalIssues += issues.length;

  const actionableIssues = issues.filter((issue) => issue.status !== 'wont_fix' && issue.status !== 'fixed');

  for (const issue of actionableIssues) {
    try {
      const segments = await draftSegmentStore.getByChapter(chapter.id);
      const sortedSegments = [...segments].sort((a, b) => a.segmentIndex - b.segmentIndex);
      const lastSegment = sortedSegments[sortedSegments.length - 1];
      const revisionSkillConfig = skillConfig.skillConfigs['revision-skill'];

      await handleRevisionSkill({
        projectId,
        chapterId: chapter.id,
        segmentId: lastSegment?.id,
        originalText: issue.excerpt || '',
        suggestion: issue.suggestion || issue.title,
        goals: [],
        constraints: [],
        applyMode: 'replace',
        reference_examples: revisionSkillConfig.referenceExamples,
        technique_directives: revisionSkillConfig.techniqueDirectives,
      } as RevisionSkillInput);

      chapterReport.revisedIssues.push(issue.id);
      workflowResult.results.totalRevisedIssues += 1;
    } catch (error) {
      chapterReport.failedIssues.push({
        issueId: issue.id,
        reason: error instanceof Error ? error.message : String(error),
      });
    }
  }
}

async function getChapterIssues(projectId: string, chapterId: string): Promise<Array<{
  id: string;
  title: string;
  status: string;
  excerpt?: string;
  suggestion?: string;
}>> {
  // Import issue store dynamically to avoid circular deps
  const { issueStore } = await import('@/lib/db/projects-store');
  return issueStore.getByChapter(chapterId) as Promise<Array<{
    id: string;
    title: string;
    status: string;
    excerpt?: string;
    suggestion?: string;
  }>>;
}

async function getDraftWordCount(projectId: string, chapterId: string): Promise<{ totalWordCount: number }> {
  const segments = await draftSegmentStore.getByChapter(chapterId);
  const totalWordCount = segments.reduce((sum, seg) => sum + countWords(seg.content), 0);
  return { totalWordCount };
}

function selectOutlineVolumes(
  outline: BookOutline,
  targetChapters: number
): BookOutline['volumes'] {
  const selectedVolumes: BookOutline['volumes'] = [];
  let remaining = targetChapters;

  for (const volume of outline.volumes) {
    if (remaining <= 0) break;

    const chosenChapters = volume.chapters.slice(0, remaining);
    if (chosenChapters.length === 0) continue;

    selectedVolumes.push({
      ...volume,
      chapters: chosenChapters,
    });

    remaining -= chosenChapters.length;
  }

  if (remaining > 0) {
    console.warn(`Outline only produced ${targetChapters - remaining} chapters, not enough for workflow.`);
  }

  return selectedVolumes;
}

function getWordTargetPlan(targetLength: TargetLength, targetChapters: number): {
  targetTotalWords: number;
  minTotalWords: number;
  targetWordsPerChapter: number;
  minWordsPerChapter: number;
} {
  const targetByLength: Record<TargetLength, { target: number; min: number }> = {
    short: { target: 6000, min: 4800 },
    mid: { target: 30000, min: 24000 },
    long: { target: 80000, min: 65000 },
  };

  const plan = targetByLength[targetLength] || targetByLength.mid;
  const safeChapterCount = Math.max(targetChapters, 1);

  return {
    targetTotalWords: plan.target,
    minTotalWords: plan.min,
    targetWordsPerChapter: Math.ceil(plan.target / safeChapterCount),
    minWordsPerChapter: Math.ceil(plan.min / safeChapterCount),
  };
}

function countWords(text: string): number {
  return text.replace(/\s+/g, '').length;
}
